const CONSTANTS = {
    MAX_NAME_LENGTH: 5,
    MIN_NAME_LENGTH: 1,
    RAMDOM_NUMBER_MIN: 0,
    RAMDOM_NUMBER_MAX: 9,
    RANDIM_NUMBER_THRESHOLD: 4,
    POSITION_MARK: "-",
    ERROR_PREFIX : "[ERROR]"
};

export default CONSTANTS;